<?php

namespace Database\Seeders;

use App\Models\Helium\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['code' => 'AF', 'name' => 'Afghanistan', 'arabic' => 'أفغانستان',],
            ['code' => 'AL', 'name' => 'Albania', 'arabic' => 'ألبانيا',],
            ['code' => 'AX', 'name' => 'Aland Islands', 'arabic' => 'جزر آلاند',],
            ['code' => 'DZ', 'name' => 'Algeria', 'arabic' => 'الجزائر',],
            ['code' => 'AS', 'name' => 'American Samoa', 'arabic' => 'ساموا-الأمريكي',],
            ['code' => 'AD', 'name' => 'Andorra', 'arabic' => 'أندورا',],
            ['code' => 'AO', 'name' => 'Angola', 'arabic' => 'أنغولا',],
            ['code' => 'AI', 'name' => 'Anguilla', 'arabic' => 'أنغويلا',],
            ['code' => 'AQ', 'name' => 'Antarctica', 'arabic' => 'أنتاركتيكا',],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'arabic' => 'أنتيغوا وبربودا'],
            ['code' => 'AR', 'name' => 'Argentina', 'arabic' => 'الأرجنتين',],
            ['code' => 'AM', 'name' => 'Armenia', 'arabic' => 'أرمينيا',],
            ['code' => 'AW', 'name' => 'Aruba', 'arabic' => 'أروبه',],
            ['code' => 'AU', 'name' => 'Australia', 'arabic' => 'أستراليا',],
            ['code' => 'AT', 'name' => 'Austria', 'arabic' => 'النمسا',],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'arabic' => 'أذربيجان',],
            ['code' => 'BS', 'name' => 'Bahamas', 'arabic' => 'الباهاماس',],
            ['code' => 'BH', 'name' => 'Bahrain', 'arabic' => 'البحرين',],
            ['code' => 'BD', 'name' => 'Bangladesh', 'arabic' => 'بنغلاديش',],
            ['code' => 'BB', 'name' => 'Barbados', 'arabic' => 'بربادوس',],
            ['code' => 'BY', 'name' => 'Belarus', 'arabic' => 'روسيا البيضاء',],
            ['code' => 'BE', 'name' => 'Belgium', 'arabic' => 'بلجيكا',],
            ['code' => 'BZ', 'name' => 'Belize', 'arabic' => 'بيليز',],
            ['code' => 'BJ', 'name' => 'Benin', 'arabic' => 'بنين',],
            ['code' => 'BL', 'name' => 'Saint Barthelemy','سان بارتيلمي',],
            ['code' => 'BM', 'name' => 'Bermuda', 'arabic' => 'جزر برمودا'],
            ['code' => 'BT', 'name' => 'Bhutan', 'arabic' => 'بوتان'],
            ['code' => 'BO', 'name' => 'Bolivia', 'arabic' => 'بوليفيا'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'arabic' => 'البوسنة و الهرسك',],
            ['code' => 'BW', 'name' => 'Botswana', 'arabic' => 'بوتسوانا',],
            ['code' => 'BV', 'name' => 'Bouvet Island', 'arabic' => 'جزيرة بوفيه',],
            ['code' => 'BR', 'name' => 'Brazil', 'arabic' => 'البرازيل',],
            ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'arabic' => 'إقليم المحيط الهندي البريطاني',],
            ['code' => 'BN', 'name' => 'Brunei Darussalam', 'arabic' => 'بروني',],
            ['code' => 'BG', 'name' => 'Bulgaria', 'arabic' => 'بلغاريا',],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'arabic' => 'بوركينا فاسو',],
            ['code' => 'BI', 'name' => 'Burundi', 'arabic' => 'بوروندي',],
            ['code' => 'KH', 'name' => 'Cambodia', 'arabic' => 'كمبوديا',],
            ['code' => 'CM', 'name' => 'Cameroon', 'arabic' => 'كاميرون',],
            ['code' => 'CA', 'name' => 'Canada', 'arabic' => 'كندا',],
            ['code' => 'CV', 'name' => 'Cape Verde', 'arabic' => 'الرأس الأخضر',],
            ['code' => 'KY', 'name' => 'Cayman Islands', 'arabic' => 'جزر كايمان',],
            ['code' => 'CF', 'name' => 'Central African Republic', 'arabic' => 'جمهورية أفريقيا الوسطى',],
            ['code' => 'TD', 'name' => 'Chad', 'arabic' => 'تشاد',],
            ['code' => 'CL', 'name' => 'Chile', 'arabic' => 'شيلي',],
            ['code' => 'CN', 'name' => 'China', 'arabic' => 'الصين',],
            ['code' => 'CX', 'name' => 'Christmas Island', 'arabic' => 'جزيرة عيد الميلاد',],
            ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'arabic' => 'جزر كوكوس',],
            ['code' => 'CO', 'name' => 'Colombia', 'arabic' => 'كولومبيا',],
            ['code' => 'KM', 'name' => 'Comoros', 'arabic' => 'جزر القمر',],
            ['code' => 'CG', 'name' => 'Congo', 'arabic' => 'الكونغو',],
            ['code' => 'CK', 'name' => 'Cook Islands', 'arabic' => 'جزر كوك',],
            ['code' => 'CR', 'name' => 'Costa Rica', 'arabic' => 'كوستاريكا',],
            ['code' => 'HR', 'name' => 'Croatia', 'arabic' => 'كرواتيا',],
            ['code' => 'CU', 'name' => 'Cuba', 'arabic' => 'كوبا',],
            ['code' => 'CY', 'name' => 'Cyprus', 'arabic' => 'قبرص',],
            ['code' => 'CW', 'name' => 'Curaçao', 'arabic' => 'كوراساو',],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'arabic' => 'الجمهورية التشيكية',],
            ['code' => 'DK', 'name' => 'Denmark', 'arabic' => 'الدانمارك',],
            ['code' => 'DJ', 'name' => 'Djibouti', 'arabic' => 'جيبوتي',],
            ['code' => 'DM', 'name' => 'Dominica', 'arabic' => 'دومينيكا',],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'arabic' =>'الجمهورية الدومينيكية'],
            ['code' => 'EC', 'name' => 'Ecuador', 'arabic' => 'إكوادور',],
            ['code' => 'EG', 'name' => 'Egypt', 'arabic' => 'مصر',],
            ['code' => 'SV', 'name' => 'El Salvador', 'arabic' => 'إلسلفادور',],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'arabic' => 'غينيا الاستوائي',],
            ['code' => 'ER', 'name' => 'Eritrea', 'arabic' => 'إريتريا',],
            ['code' => 'EE', 'name' => 'Estonia', 'arabic' => 'استونيا',],
            ['code' => 'ET', 'name' => 'Ethiopia', 'arabic' => 'أثيوبيا',],
            ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'arabic' => 'جزر فوكلاند',],
            ['code' => 'FO', 'name' => 'Faroe Islands', 'arabic' => 'جزر فارو',],
            ['code' => 'FJ', 'name' => 'Fiji', 'arabic' => 'فيجي',],
            ['code' => 'FI', 'name' => 'Finland', 'arabic' => 'فنلندا',],
            ['code' => 'FR', 'name' => 'France', 'arabic' => 'فرنسا',],
            ['code' => 'GF', 'name' => 'French Guiana', 'arabic' => 'غويانا الفرنسية',],
            ['code' => 'PF', 'name' => 'French Polynesia', 'arabic' => 'بولينيزيا الفرنسية',],
            ['code' => 'TF', 'name' => 'French Southern and Antarctic Lands', 'arabic' => 'أراض فرنسية جنوبية'],
            ['code' => 'GA', 'name' => 'Gabon', 'arabic' => 'الغابون',],
            ['code' => 'GM', 'name' => 'Gambia', 'arabic' => 'غامبيا',],
            ['code' => 'GE', 'name' => 'Georgia', 'arabic' => 'جيورجيا',],
            ['code' => 'DE', 'name' => 'Germany', 'arabic' => 'ألمانيا',],
            ['code' => 'GH', 'name' => 'Ghana', 'arabic' => 'غانا',],
            ['code' => 'GI', 'name' => 'Gibraltar', 'arabic' => 'جبل طارق',],
            ['code' => 'GG', 'name' => 'Guernsey', 'arabic' => 'غيرنزي',],
            ['code' => 'GR', 'name' => 'Greece', 'arabic' => 'اليونان',],
            ['code' => 'GL', 'name' => 'Greenland', 'arabic' => 'جرينلاند',],
            ['code' => 'GD', 'name' => 'Grenada', 'arabic' => 'غرينادا',],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'arabic' => 'جزر جوادلوب',],
            ['code' => 'GU', 'name' => 'Guam', 'arabic' => 'جوام',],
            ['code' => 'GT', 'name' => 'Guatemala', 'arabic' => 'غواتيمال',],
            ['code' => 'GN', 'name' => 'Guinea', 'arabic' => 'غينيا',],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'arabic' => 'غينيا-بيساو',],
            ['code' => 'GY', 'name' => 'Guyana', 'arabic' => 'غيانا',],
            ['code' => 'HT', 'name' => 'Haiti', 'arabic' => 'هايتي',],
            ['code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'arabic' => 'جزيرة هيرد وجزر ماكدونالد',],
            ['code' => 'HN', 'name' => 'Honduras', 'arabic' => 'هندوراس',],
            ['code' => 'HK', 'name' => 'Hong Kong', 'arabic' => 'هونغ كونغ',],
            ['code' => 'HU', 'name' => 'Hungary', 'arabic' => 'المجر',],
            ['code' => 'IS', 'name' => 'Iceland', 'arabic' => 'آيسلندا',],
            ['code' => 'IN', 'name' => 'India', 'arabic' => 'الهند',],
            ['code' => 'IM', 'name' => 'Isle of Man', 'arabic' => 'جزيرة مان',],
            ['code' => 'ID', 'name' => 'Indonesia', 'arabic' => 'أندونيسيا',],
            ['code' => 'IR', 'name' => 'Iran', 'arabic' => 'إيران',],
            ['code' => 'IQ', 'name' => 'Iraq', 'arabic' => 'العراق',],
            ['code' => 'IE', 'name' => 'Ireland', 'arabic' => 'إيرلندا',],
             ['code' => 'IT', 'name' => 'Italy', 'arabic' => 'إيطاليا',],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'arabic' => 'ساحل العاج',],
            ['code' => 'JE', 'name' => 'Jersey', 'arabic' => 'جيرزي',],
            ['code' => 'JM', 'name' => 'Jamaica', 'arabic' => 'جمايكا',],
            ['code' => 'JP', 'name' => 'Japan', 'arabic' => 'اليابان',],
            ['code' => 'JO', 'name' => 'Jordan', 'arabic' => 'الأردن',],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'arabic' => 'كازاخستان',],
            ['code' => 'KE', 'name' => 'Kenya', 'arabic' => 'كينيا',],
            ['code' => 'KI', 'name' => 'Kiribati', 'arabic' => 'كيريباتي',],
            ['code' => 'KP', 'name' => 'Korea(North Korea)', 'arabic' => 'كوريا الشمالية',],
            ['code' => 'KR', 'name' => 'Korea(South Korea)', 'arabic' => 'كوريا الجنوبية',],
            ['code' => 'XK', 'name' => 'Kosovo', 'arabic' => 'كوسوفو',],
            ['code' => 'KW', 'name' => 'Kuwait', 'arabic' => 'الكويت',],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'arabic' => 'قيرغيزستان',],
            ['code' => 'LA', 'name' => 'Lao PDR', 'arabic' => 'لاوس',],
            ['code' => 'LV', 'name' => 'Latvia', 'arabic' => 'لاتفيا',],
            ['code' => 'LB', 'name' => 'Lebanon', 'arabic' => 'لبنان',],
            ['code' => 'LS', 'name' => 'Lesotho', 'arabic' => 'ليسوتو',],
            ['code' => 'LR', 'name' => 'Liberia', 'arabic' => 'ليبيريا',],
            ['code' => 'LY', 'name' => 'Libya', 'arabic' => 'ليبيا',],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'arabic' => 'ليختنشتين',],
            ['code' => 'LT', 'name' => 'Lithuania', 'arabic' => 'لتوانيا',],
            ['code' => 'LU', 'name' => 'Luxembourg', 'arabic' => 'لوكسمبورغ',],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'arabic' => 'سريلانكا',],
            ['code' => 'MO', 'name' => 'Macau', 'arabic' => 'ماكاو',],
            ['code' => 'MK', 'name' => 'Macedonia', 'arabic' => 'مقدونيا',],
            ['code' => 'MG', 'name' => 'Madagascar', 'arabic' => 'مدغشقر',],
            ['code' => 'MW', 'name' => 'Malawi', 'arabic' => 'مالاوي',],
            ['code' => 'MY', 'name' => 'Malaysia', 'arabic' => 'ماليزيا',],
            ['code' => 'MV', 'name' => 'Maldives', 'arabic' => 'المالديف',],
            ['code' => 'ML', 'name' => 'Mali', 'arabic' => 'مالي',],
            ['code' => 'MT', 'name' => 'Malta', 'arabic' => 'مالطا',],
            ['code' => 'MH', 'name' =>  'Marshall Islands', 'arabic' => 'جزر مارشال'],
            ['code' => 'MQ', 'name' => 'Martinique', 'arabic' => 'مارتينيك',],
            ['code' => 'MR', 'name' => 'Mauritania', 'arabic' => 'موريتانيا',],
            ['code' => 'MU', 'name' => 'Mauritius', 'arabic' => 'موريشيوس',],
            ['code' => 'YT', 'name' => 'Mayotte', 'arabic' => 'مايوت',],
            ['code' => 'MX', 'name' => 'Mexico', 'arabic' => 'المكسيك',],
            ['code' => 'FM', 'name' => 'Micronesia', 'arabic' => 'مايكرونيزيا',],
            ['code' => 'MD', 'name' => 'Moldova', 'arabic' => 'مولدافيا',],
            ['code' => 'MC', 'name' => 'Monaco', 'arabic' => 'موناكو',],
            ['code' => 'MN', 'name' => 'Mongolia', 'arabic' => 'منغوليا',],
            ['code' => 'ME', 'name' => 'Montenegro', 'arabic' => 'الجبل الأسود',],
            ['code' => 'MS', 'name' => 'Montserrat', 'arabic' => 'مونتسيرات',],
            ['code' => 'MA', 'name' => 'Morocco', 'arabic' => 'المغرب',],
            ['code' => 'MZ', 'name' => 'Mozambique', 'arabic' => 'موزمبيق',],
            ['code' => 'MM', 'name' => 'Myanmar', 'arabic' => 'ميانمار',],
            ['code' => 'NA', 'name' => 'Namibia', 'arabic' => 'ناميبيا',],
            ['code' => 'NR', 'name' => 'Nauru', 'arabic' => 'نورو',],
            ['code' => 'NP', 'name' => 'Nepal', 'arabic' => 'نيبال',],
            ['code' => 'NL', 'name' => 'Netherlands', 'arabic' => 'هولندا',],
            ['code' => 'AN', 'name' => 'Netherlands Antilles', 'arabic' => 'جزر الأنتيل الهولندي',],
            ['code' => 'NC', 'name' => 'New Caledonia', 'arabic' => 'كاليدونيا الجديدة',],
            ['code' => 'NZ', 'name' => 'New Zealand', 'arabic' => 'نيوزيلندا',],
            ['code' => 'NI', 'name' => 'Nicaragua', 'arabic' => 'نيكاراجوا',],
            ['code' => 'NE', 'name' => 'Niger', 'arabic' => 'النيجر',],
            ['code' => 'NG', 'name' => 'Nigeria', 'arabic' => 'نيجيريا',],
            ['code' => 'NU', 'name' => 'Niue', 'arabic' => 'ني',],
            ['code' => 'NF', 'name' => 'Norfolk Island', 'arabic' => 'جزيرة نورفولك',],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'arabic' => 'جزر ماريانا الشمالية',],
            ['code' => 'NO', 'name' => 'Norway', 'arabic' => 'النرويج',],
            ['code' => 'OM', 'name' => 'Oman', 'arabic' => 'عمان',],
            ['code' => 'PK', 'name' => 'Pakistan', 'arabic' => 'باكستان',],
            ['code' => 'PW', 'name' => 'Palau', 'arabic' => 'بالاو',],
            ['code' => 'PS', 'name' => 'Palestine', 'arabic' => 'فلسطين',],
            ['code' => 'PA', 'name' => 'Panama', 'arabic' => 'بنما',],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'arabic' => 'بابوا غينيا الجديدة',],
            ['code' => 'PY', 'name' => 'Paraguay', 'arabic' => 'باراغواي',],
            ['code' => 'PE', 'name' => 'Peru', 'arabic' => 'بيرو',],
            ['code' => 'PH', 'name' => 'Philippines', 'arabic' => 'الفليبين',],
            ['code' => 'PN', 'name' => 'Pitcairn', 'arabic' => 'بيتكيرن',],
            ['code' => 'PL', 'name' => 'Poland', 'arabic' => 'بولندا',],
            ['code' => 'PT', 'name' => 'Portugal', 'arabic' => 'البرتغال',],
            ['code' => 'PR', 'name' => 'Puerto Rico','بورتو ريكو',],
            ['code' => 'QA', 'name' => 'Qatar', 'arabic' => 'قطر',],
            ['code' => 'RE', 'name' => 'Reunion Island', 'arabic' => 'ريونيون',],
            ['code' => 'RO', 'name' => 'Romania', 'arabic' => 'رومانيا',],
            ['code' => 'RU', 'name' => 'Russian', 'arabic' => 'روسيا',],
            ['code' => 'RW', 'name' => 'Rwanda', 'arabic' => 'رواندا',],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'arabic' => 'سانت كيتس ونيفس,',],
            ['code' => 'MF', 'name' => 'Saint Martin (French part)', 'arabic' => 'ساينت مارتن فرنسي',],
            ['code' => 'SX', 'name' => 'Sint Maarten (Dutch part)', 'arabic' => 'ساينت مارتن هولندي',],
            ['code' => 'LC', 'name' => 'Saint Pierre and Miquelon', 'arabic' => 'سان بيير وميكلون',],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'arabic' => 'سانت فنسنت وجزر غرينادين',],
            ['code' => 'WS', 'name' => 'Samoa', 'arabic' => 'ساموا',],
            ['code' => 'SM', 'name' => 'San Marino', 'arabic' => 'سان مارينو',],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'arabic' => 'ساو تومي وبرينسيبي',],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'arabic' => 'المملكة العربية السعودية',],
            ['code' => 'SN', 'name' => 'Senegal', 'arabic' => 'السنغال',],
            ['code' => 'RS', 'name' => 'Serbia', 'arabic' => 'صربيا',],
            ['code' => 'SC', 'name' => 'Seychelles', 'arabic' => 'سيشيل',],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'arabic' => 'سيراليون',],
            ['code' => 'SG', 'name' => 'Singapore', 'arabic' => 'سنغافورة',],
            ['code' => 'SK', 'name' => 'Slovakia', 'arabic' => 'سلوفاكيا',],
            ['code' => 'SI', 'name' => 'Slovenia', 'arabic' => 'سلوفينيا',],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'arabic' => 'جزر سليمان',],
            ['code' => 'SO', 'name' => 'Somalia', 'arabic' => 'الصومال',],
            ['code' => 'ZA', 'name' => 'South Africa', 'arabic' => 'جنوب أفريقيا',],
            ['code' => 'GS', 'name' => 'South Georgia and the South Sandwich', 'arabic' => 'المنطقة القطبية الجنوبية',],
            ['code' => 'SS', 'name' => 'South Sudan', 'arabic' => 'السودان الجنوبي',],
            ['code' => 'ES', 'name' => 'Spain', 'arabic' => 'إسبانيا',],
            ['code' => 'SH', 'name' => 'Saint Helena', 'arabic' => 'سانت هيلانة',],
            ['code' => 'SD', 'name' => 'Sudan', 'arabic' => 'السودان',],
            ['code' => 'SR', 'name' => 'Suriname', 'arabic' => 'سورينام',],
            ['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'arabic' => 'سفالبارد ويان ماين',],
            ['code' => 'SZ', 'name' => 'Swaziland', 'arabic' => 'سوازيلند',],
            ['code' => 'SE', 'name' => 'Sweden', 'arabic' => 'السويد',],
            ['code' => 'CH', 'name' => 'Switzerland', 'arabic' => 'سويسرا',],
            ['code' => 'SY', 'name' => 'Syria', 'arabic' => 'سوريا',],
            ['code' => 'TW', 'name' => 'Taiwan', 'arabic' => 'تايوان',],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'arabic' => 'طاجيكستان',],
            ['code' => 'TZ', 'name' => 'Tanzania', 'arabic' => 'تنزانيا',],
            ['code' => 'TH', 'name' => 'Thailand', 'arabic' => 'تايلندا',],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'arabic' => 'تيمور الشرقية',],
            ['code' => 'TG', 'name' => 'Togo', 'arabic' => 'توغو',],
            ['code' => 'TK', 'name' => 'Tokelau', 'arabic' => 'توكيلاو',],
            ['code' => 'TO', 'name' => 'Tonga', 'arabic' => 'تونغا',],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'arabic' => 'ترينيداد وتوباغو',],
            ['code' => 'TN', 'name' => 'Tunisia', 'arabic' => 'تونس',],
            ['code' => 'TR', 'name' => 'Turkey', 'arabic' => 'تركيا',],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'arabic' => 'تركمانستان',],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'arabic' => 'جزر توركس وكايكوس',],
            ['code' => 'TV', 'name' => 'Tuvalu', 'arabic' => 'توفالو',],
            ['code' => 'UG', 'name' => 'Uganda', 'arabic' => 'أوغندا',],
            ['code' => 'UA', 'name' => 'Ukraine', 'arabic' => 'أوكرانيا',],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'arabic' => 'الإمارات العربية المتحدة',],
            ['code' => 'GB', 'name' => 'United Kingdom', 'arabic' => 'المملكة المتحدة',],
            ['code' => 'US', 'name' => 'United States', 'arabic' => 'الولايات المتحدة',],
            ['code' => 'UM', 'name' => 'US Minor Outlying Islands', 'arabic' => 'قائمة الولايات والمناطق الأمريكية',],
            ['code' => 'UY', 'name' => 'Uruguay', 'arabic' => 'أورغواي',],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'arabic' => 'أوزباكستان',],
            ['code' => 'VU', 'name' => 'Vanuatu', 'arabic' => 'فانواتو',],
            ['code' => 'VE', 'name' => 'Venezuela', 'arabic' => 'فنزويلا',],
            ['code' => 'VN', 'name' => 'Vietnam', 'arabic' => 'فيتنام',],
            ['code' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'arabic' => 'الجزر العذراء الأمريكي',],
            ['code' => 'VA', 'name' => 'Vatican City', 'arabic' => 'فنزويلا',],
            ['code' => 'WF', 'name' => 'Wallis and Futuna Islands', 'arabic' => 'والس وفوتونا',],
            ['code' => 'EH', 'name' => 'Western Sahara', 'arabic' => 'الصحراء الغربية',],
            ['code' => 'YE', 'name' => 'Yemen', 'arabic' => 'اليمن',],
            ['code' => 'ZM', 'name' => 'Zambia', 'arabic' => 'زامبيا',],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'arabic' => 'زمبابوي',],
        ];

        Country::insert($countries);
    }
}
